<?php defined( 'ABSPATH' ) || exit; $notice = isset( $_GET['radar_notice'] ) ? sanitize_key( wp_unslash( $_GET['radar_notice'] ) ) : ''; ?>
<div class="srf-shell srf-studies" id="radar-saved-studies">
	<header class="srf-page-head"><span>Private Verified-Doctor Workspace</span><h1>Radar Saved Studies</h1><p>Private educational notes linked to published Radar entries. Patient-identifying information is prohibited.</p><a class="srf-button" href="<?php echo esc_url( $radar_url ); ?>">Open Radar</a></header>
	<?php if ( 'saved' === $notice ) : ?><div class="srf-message is-success" role="status">Your private Radar study was saved.</div><?php elseif ( 'deleted' === $notice ) : ?><div class="srf-message" role="status">The saved study was deleted.</div><?php elseif ( 'rate_limited' === $notice ) : ?><div class="srf-message is-error" role="alert">Please wait a few seconds before saving another study.</div><?php elseif ( 'limit_reached' === $notice ) : ?><div class="srf-message is-error" role="alert">The maximum of 500 saved studies has been reached. Delete an older study before saving another.</div><?php elseif ( $notice ) : ?><div class="srf-message is-error" role="alert">The study could not be saved. Select entries, add a title, and confirm that no patient identity is included.</div><?php endif; ?>
	<div class="srf-study-list">
		<?php if ( $items ) : foreach ( $items as $item ) : $entry_ids = array_slice( array_filter( array_map( 'absint', explode( ',', $item->entry_ids ) ) ), 0, 3 ); ?>
		<article class="srf-study-card"><header><div><span>Private Study #<?php echo absint( $item->id ); ?></span><h2><?php echo esc_html( $item->title ); ?></h2></div><small>Updated <?php echo esc_html( get_date_from_gmt( $item->updated_at, get_option( 'date_format' ) ) ); ?></small></header><h3>Selected Radar Entries</h3><ul><?php foreach ( $entry_ids as $entry_id ) : ?><li><?php if ( 'publish' === get_post_status( $entry_id ) ) : ?><a href="<?php echo esc_url( get_permalink( $entry_id ) ); ?>"><?php echo esc_html( get_the_title( $entry_id ) ); ?></a><?php else : ?>Entry no longer public<?php endif; ?></li><?php endforeach; ?></ul><?php if ( $item->notes ) : ?><h3>Private Research Notes</h3><p><?php echo nl2br( esc_html( $item->notes ) ); ?></p><?php endif; ?><form action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" method="post"><input type="hidden" name="action" value="srf_delete_study"><input type="hidden" name="study_id" value="<?php echo absint( $item->id ); ?>"><?php wp_nonce_field( 'srf_delete_study_' . $item->id ); ?><button class="srf-delete" type="submit" aria-label="<?php echo esc_attr( 'Delete private Radar study ' . $item->title ); ?>">Delete Study</button></form></article>
		<?php endforeach; else : ?><div class="srf-empty"><h2>No saved studies yet</h2><p>Select up to three published entries on Radar and save an anonymous educational study.</p><a class="srf-button" href="<?php echo esc_url( $radar_url ); ?>">Start a Radar Study</a></div><?php endif; ?>
	</div>
	<p class="srf-disclaimer">Do not store patient names, contact details, record numbers, addresses, or other identifying information in Radar studies.</p>
</div>
