<?php
$view = RSR_Routes::view();
get_header();
?>
<div class="rsr-page rsr-trends-page" dir="<?php echo is_rtl() ? 'rtl' : 'ltr'; ?>">
    <?php RSR_Routes::context_controls(['fallback' => home_url('/')]); ?>
    <header class="rsr-hero"><div><p class="rsr-eyebrow"><?php esc_html_e('Daily · weekly · monthly · yearly', RSR_TEXT_DOMAIN); ?></p><h1><?php esc_html_e('Trend Intelligence', RSR_TEXT_DOMAIN); ?></h1><p><?php esc_html_e('Editorially approved, reproducible reports with source, method, geography, window, confidence, and freshness.', RSR_TEXT_DOMAIN); ?></p></div><a class="rsr-button rsr-button-secondary" href="<?php echo esc_url($view['urls']['radar']); ?>"><?php esc_html_e('Open Radar', RSR_TEXT_DOMAIN); ?></a></header>
    <aside class="rsr-safety"><strong><?php esc_html_e('Interpret carefully:', RSR_TEXT_DOMAIN); ?></strong> <?php esc_html_e('Source activity is not disease prevalence and is not clinical advice.', RSR_TEXT_DOMAIN); ?></aside>
    <section class="rsr-panel"><form method="get" action="<?php echo esc_url($view['urls']['trends']); ?>" class="rsr-inline-form"><div class="rsr-field"><label for="trend-window"><?php esc_html_e('Window', RSR_TEXT_DOMAIN); ?></label><select id="trend-window" name="window"><option value=""><?php esc_html_e('All windows', RSR_TEXT_DOMAIN); ?></option><?php foreach (['daily','weekly','monthly','yearly'] as $window) : ?><option value="<?php echo esc_attr($window); ?>" <?php selected(isset($_GET['window']) ? sanitize_key(wp_unslash((string)$_GET['window'])) : '', $window); ?>><?php echo esc_html(ucfirst($window)); ?></option><?php endforeach; ?></select></div><div class="rsr-field"><label for="trend-geography"><?php esc_html_e('Geography key', RSR_TEXT_DOMAIN); ?></label><input id="trend-geography" name="geography" value="<?php echo esc_attr(isset($_GET['geography']) ? sanitize_key(wp_unslash((string)$_GET['geography'])) : ''); ?>"></div><button class="rsr-button" type="submit"><?php esc_html_e('Filter', RSR_TEXT_DOMAIN); ?></button></form></section>
    <section class="rsr-results"><h2><?php esc_html_e('Published reports', RSR_TEXT_DOMAIN); ?></h2><?php if (empty($view['reports'])) : ?><div class="rsr-empty"><h3><?php esc_html_e('No approved report is public yet', RSR_TEXT_DOMAIN); ?></h3><p><?php esc_html_e('Ingestion does not publish automatically. A report appears only after analyst and editorial approval.', RSR_TEXT_DOMAIN); ?></p></div><?php else : ?><div class="rsr-card-grid"><?php foreach ((array)$view['reports'] as $report) : $topics=(array)($report['results']['topics']??[]); ?><article class="rsr-card rsr-trend-card"><header><div><p class="rsr-eyebrow"><?php echo esc_html((string)$report['window_type']); ?> · <?php echo esc_html((string)$report['geography']); ?></p><h3><?php echo esc_html(sprintf(__('Trend report ending %s', RSR_TEXT_DOMAIN), wp_date(get_option('date_format'), strtotime((string)$report['window_end_utc'])))); ?></h3></div><span class="rsr-status <?php echo !empty($report['stale']) ? 'rsr-status-warning' : ''; ?>"><?php echo !empty($report['stale']) ? esc_html__('Stale', RSR_TEXT_DOMAIN) : esc_html__('Current', RSR_TEXT_DOMAIN); ?></span></header><ol class="rsr-trend-preview"><?php foreach (array_slice($topics,0,5) as $topic) : ?><li><span><?php echo esc_html((string)$topic['topic_label']); ?></span><meter min="0" max="100" value="<?php echo esc_attr((string)$topic['score']); ?>"><?php echo esc_html((string)$topic['score']); ?></meter></li><?php endforeach; ?></ol><p class="rsr-meta"><?php printf(esc_html__('Confidence %.0f%% · %d sources', RSR_TEXT_DOMAIN), (float)$report['confidence']*100, count((array)$report['sources'])); ?></p><a class="rsr-text-link" href="<?php echo esc_url((string)$report['canonical_url']); ?>"><?php esc_html_e('Read methodology and results', RSR_TEXT_DOMAIN); ?></a></article><?php endforeach; ?></div><?php endif; ?></section>
</div>
<?php get_footer(); ?>
